dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: test-gradle-app-26202
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test26235
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test26238
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test26350
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
